name: Android CI Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git describe to work
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Set build number from git
        run: |
          export GIT_COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "GIT_COMMIT_COUNT=$GIT_COMMIT_COUNT" >> $GITHUB_ENV
          echo "Build number: $GIT_COMMIT_COUNT"
      
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace --no-daemon
        env:
          GIT_COMMIT_COUNT: ${{ env.GIT_COMMIT_COUNT }}
      
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace --no-daemon
        continue-on-error: false
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            app/build/reports/tests/
            app/build/test-results/
          retention-days: 30
      
      - name: Upload debug APKs
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 30
      
      - name: Build release APK (unsigned)
        run: ./gradlew assembleRelease --stacktrace --no-daemon
        env:
          GIT_COMMIT_COUNT: ${{ env.GIT_COMMIT_COUNT }}
      
      - name: Upload release APKs
        uses: actions/upload-artifact@v4
        with:
          name: release-apks-unsigned
          path: app/build/outputs/apk/release/*.apk
          retention-days: 30
      
      - name: Generate build summary
        if: always()
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Build Information" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Number:** ${{ env.GIT_COMMIT_COUNT }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -d "app/build/outputs/apk/debug" ]; then
            echo "### Debug APKs Built" >> $GITHUB_STEP_SUMMARY
            ls -lh app/build/outputs/apk/debug/*.apk | awk '{print "- " $9 " (" $5 ")"}' >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -d "app/build/outputs/apk/release" ]; then
            echo "### Release APKs Built" >> $GITHUB_STEP_SUMMARY
            ls -lh app/build/outputs/apk/release/*.apk | awk '{print "- " $9 " (" $5 ")"}' >> $GITHUB_STEP_SUMMARY
          fi

