name: Code Quality Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  lint:
    # Use available Codeberg runner label
    runs-on: codeberg-medium
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Run Android Lint
        run: ./gradlew lintDebug --stacktrace --no-daemon
        continue-on-error: true
      
      - name: Upload lint results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: |
            app/build/reports/lint-results-*.html
            app/build/reports/lint-results-*.xml
          retention-days: 30
      
      - name: Check Kotlin code style
        run: ./gradlew build --dry-run --stacktrace --no-daemon
      
      - name: Generate lint summary
        if: always()
        run: |
          echo "## Code Quality Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Lint Results" >> $GITHUB_STEP_SUMMARY
          
          if [ -f "app/build/reports/lint-results-debug.xml" ]; then
            echo "Lint report generated successfully" >> $GITHUB_STEP_SUMMARY
            echo "Check the artifacts for detailed results" >> $GITHUB_STEP_SUMMARY
          else
            echo "No lint results found" >> $GITHUB_STEP_SUMMARY
          fi

